//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agreement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agreement.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program 100% open source and free.
        ///If you bought it, then congratulations on being cheated!
        ///
        ///This program make by @manesec, but still need some time to upgrade.
        ///
        ///1. We do not collect any data from users.
        ///2. This program is currently a beta stage, many features are not perfect, there are problems please submit issues in github.
        ///3. We are not responsible for any loss of user data, nor do we need to damage user data, and you agree to be responsible for any loss of data resulting from this procedure [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ADDITION_TEXT {
            get {
                return ResourceManager.GetString("ADDITION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU GENERAL PUBLIC LICENSE
        ///Version 3, 29 June 2007
        ///
        ///Copyright © 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;
        ///
        ///Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.
        ///
        ///Preamble
        ///The GNU General Public License is a free, copyleft license for software and other kinds of works.
        ///
        ///The licenses for most software and other practical works are designed to take away your freedom to share and change the works. By contrast, the GNU Genera [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TOC_TEXT {
            get {
                return ResourceManager.GetString("TOC_TEXT", resourceCulture);
            }
        }
    }
}
